### ISSUE TITLE
Null Safety 

### ISSUE THREAD

**Issue by bashiryousufy** [GoyalSidhant/dialogflow_flutter#2]
Is it possible to make this package null safe? 

I'm using this package for my chatbot app and planning to move to null safety since of the other packages requires null safety.

**Comment by GoyalSidhant** [comment]
Sure!
I'll push an update in day or two 

Thanks!

**Comment by GoyalSidhant** [comment]
Update in latest version pls check

**Comment by bashiryousufy** [comment]
Thank you @GoyalSidhant
